### ISSUE TITLE
آموزش استفاده

### ISSUE THREAD

**Issue by BarnameESF** [Luagram/LuagramProject#2]
آموزش استفاده کامل از این پروژه هم بزارید .
مثلا چطوری میشه لاگین زد چه با توکن چه از طریق شماره و ....
پروژه خوبیه . امیدوارم ادامه دار باشه.

**Comment by KhodeAmir** [comment]
شما میتونید توی گروه ما عضو بشین  و چگونگی استفاده از این کلاینت بفهمین یا پوشه EXAMPLE به دقت نگا کنید
